#!/usr/bin/env bash
# Configures a new ubuntu machine

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y


# starts nginx
sudo service nginx start

# allows nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives the user ownership to website
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creates new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarts nginx
sudo service nginx restart

echo -e "\nDone\n"
