#!/usr/bin/env bash
# Duplicate web-01 to web-02
# This script sets up Nginx on Ubuntu with specific configurations


echo -e "Updating.....\n"

function install_package() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} already installed.\n"
    fi
}

# Install Nginx
install_package nginx

echo -e "\nSetting up....\n"

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
web_dir="/var/www"
if [ -d "$web_dir" ]; then
    sudo chown -R "$USER":"$USER" "$web_dir"
    sudo chmod -R 755 "$web_dir"
else
    sudo mkdir -p "$web_dir"
    sudo chown -R "$USER":"$USER" "$web_dir"
    sudo chmod -R 755 "$web_dir"
fi

# Create directories if not present
for dir in "$web_dir"/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create new index page
echo "Hello World!" > "$web_dir"/html/index.html

# Create new error page
echo "Not a page" > "$web_dir"/html/error_404.html

# Backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Define Nginx server configuration
server_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root $web_dir/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

# Disable SC2154 for the dynamic variable $hostname
# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi

echo "Configuration completed. Nginx is now configured with the custom header X-Served-By."

