#!/usr/bin/env bash
# Function to handle SIGTERM signal
# Function to handle SIGINT signal
# Function to handle SIGQUIT signal
# Register signal handlers
# Get current PID and save it to the file
# Displaying "To infinity and beyond" indefinitely

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
