#!/usr/bin/env bash
# handle SIGTERM signal
# handle SIGINT signal
# handle SIGQUIT signal
# Register signal handlers
# Get current PID and save it to the file
# Displaying "To infinity and beyond" indefinitely

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

# Register signal handlers outside the loop
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
