#!/usr/bin/env bash
#At 4 prints bad luck from China, 9 bad luck from Japan, 17 bad luck from Italy
i=1

while [ $i -le 20 ]; do
    case $i in
        4)
            echo -e "$i \nbad luck from China"
            ;;
        9)
            echo -e "$i \nbad luck from Japan"
            ;;
        17)
            echo -e "$i \nbad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
